package com.example.utils

enum class Language(val code: String) {
    EN("English"),
    AR("العربية"),
    FR("Français")
}

object Loc {
    private val en = mapOf(
        "app_name" to "MedSync",
        "tagline" to "AI Healthcare & Medical System",
        "welcome" to "Welcome Back",
        "role_select" to "Select Your Access Role",
        "doctor" to "Doctor / Medical Staff",
        "nurse" to "Nurse / Clinic Staff",
        "pharmacist" to "Pharmacist",
        "patient" to "Patient / Guardian",
        "login" to "Sign In",
        "register" to "Create Account",
        "email" to "Email Address",
        "password" to "Password",
        "phone" to "Phone Number",
        "specialization" to "Medical Specialization",
        "emergency_contact" to "Emergency Contact Number",
        "fullname" to "Full Name",
        "submit" to "Submit & Continue",
        "logout" to "Secure Logout",
        "today_appointments" to "Today's Appointments",
        "quick_actions" to "Quick Actions",
        "ai_assistant" to "AI Med-Assistant",
        "ai_insight_bp" to "Patient #8821 showing 15% increase in BP variability. Review required before evening rounds.",
        "open_insights" to "Open Assistant",
        "stats_appointments" to "Active Appointments",
        "stats_pending" to "Pending Reports",
        "telehealth" to "Telehealth Clinic",
        "in_person" to "In-Person Consultation",
        "see_all" to "See All",
        "due_soon" to "Due Soon",
        "new_alert" to "+3 New Today",
        "chat_placeholder" to "Ask symptoms, drug warnings, dosage limits...",
        "send" to "Send",
        "clear_chat" to "Clear Conversational History",
        "sos_button" to "EMERGENCY SOS",
        "sos_pulsing" to "Tap to Broadcast GPS Location & Vital Alerts",
        "sos_sent" to "Emergency SOS Broadcast Sent! Support is on the way.",
        "pharmacy_inventory" to "Pharmacy Inventory & Expiry Alerts",
        "medication_name" to "Medication Name",
        "category" to "Category",
        "stock" to "Remaining Stock",
        "price" to "Unit Price",
        "barcode_scan" to "Simulate Barcode Scan",
        "add_medication" to "Add New Dose/Medication",
        "low_stock" to "LOW STOCK WARNING!",
        "prescription_mgr" to "Digital Prescriptions & QR Check",
        "signature_pad" to "Doctor Signature Hand-Pad",
        "clear_signature" to "Clear Handpad",
        "verify_qr" to "Verify QR Code Verifiable Credentials",
        "drug_interaction_warning" to "WARNING: Potential Interaction Detected between NSAIDs and ACE inhibitors.",
        "settings_title" to "Enterprise Sync & Language Options",
        "sync_now" to "Force Cloud Sync (Firestore)",
        "offline_mode" to "Local Offline Safe Mode Enabled",
        "language_toggle" to "System Translation language",
        "empty_appointments" to "No medical appointments scheduled",
        "analytics_summary" to "Clinical Analytics & Performance Overview",
        "admin" to "System Administrator",
        "change_passwd" to "Change Password",
        "current_passwd" to "Current Password",
        "new_passwd" to "New Password",
        "save_passwd" to "Save Password Changes",
        "receptionist" to "Receptionist / Desk Staff"
    )

    private val ar = mapOf(
        "app_name" to "ميدسينك",
        "tagline" to "النظام الذكي للرعاية الصحية والطبية",
        "welcome" to "مرحباً بك مجدداً",
        "role_select" to "اختر صلاحية الدخول الخاصة بك",
        "doctor" to "طبيب / الكادر الطبي",
        "nurse" to "ممرض / كادر العيادة",
        "pharmacist" to "الصيدلاني",
        "patient" to "مريض / مراجع",
        "login" to "تسجيل الدخول",
        "register" to "إنشاء حساب جديد",
        "email" to "البريد الإلكتروني",
        "password" to "كلمة المرور",
        "phone" to "رقم الهاتف",
        "specialization" to "التخصص الطبي",
        "emergency_contact" to "رقم الطوارئ",
        "fullname" to "الاسم الكامل",
        "submit" to "إرسال ومتابعة",
        "logout" to "تسجيل خروج آمن",
        "today_appointments" to "مواعيد اليوم والعيادات",
        "quick_actions" to "الوصول السريع",
        "ai_assistant" to "مساعد الذكاء الاصطناعي الطبي",
        "ai_insight_bp" to "يظهر المريض #8821 زيادة بنسبة 15% في تباين ضغط الدم. المراجعة مطلوبة قبل جولات المساء.",
        "open_insights" to "افتح المساعد",
        "stats_appointments" to "المواعيد النشطة",
        "stats_pending" to "التقارير المعلقة",
        "telehealth" to "عيادة عن بعد",
        "in_person" to "استشارة حضورية",
        "see_all" to "عرض الكل",
        "due_soon" to "يستحق قريباً",
        "new_alert" to "+3 طبي جديد اليوم",
        "chat_placeholder" to "اسأل عن الأعراض، تداخل الأدوية، أو الجرعات...",
        "send" to "إرسال",
        "clear_chat" to "مسح سجل المحادثة",
        "sos_button" to "نداء استغاثة SOS",
        "sos_pulsing" to "انقر لبث موقعك الجغرافي وبياناتك الحيوية لغرفة الطوارئ",
        "sos_sent" to "تم بث نداء الاستغاثة بنجاح! طواقم الإسعاف في طريقها إليك.",
        "pharmacy_inventory" to "مخزون الصيدلية وتنبيهات انتهاء الصلاحية",
        "medication_name" to "اسم الدواء",
        "category" to "الفئة",
        "stock" to "المخزون المتبقي",
        "price" to "سعر الوحدة",
        "barcode_scan" to "محاكاة قراءة الباركود",
        "add_medication" to "إضافة دواء/جرعة جديدة",
        "low_stock" to "تنبيه: مخزون منخفض جداً!",
        "prescription_mgr" to "الوصفات الطبية الرقمية وفحص الرمز QR",
        "signature_pad" to "لوحة توقيع الطبيب المعتمدة",
        "clear_signature" to "مسح التوقيع",
        "verify_qr" to "التحقق من صحة كود QR الطبي",
        "drug_interaction_warning" to "تحذير: تم اكتشاف تداخل دوائي محتمل بين NSAIDs ومثبطات ACE.",
        "settings_title" to "المزامنة السحابية وإعدادات اللغة",
        "sync_now" to "مزامنة سحابية فورية (Firestore)",
        "offline_mode" to "وضع الحفظ المحلي آمن دون اتصال",
        "language_toggle" to "لغة واجهة النظام الفرعية",
        "empty_appointments" to "لا توجد مواعيد طبية مجدولة اليوم",
        "analytics_summary" to "التحليلات العيادية والأداء العام للعيادة",
        "admin" to "مسؤول النظام والمدير",
        "change_passwd" to "تغيير كلمة المرور",
        "current_passwd" to "كلمة المرور الحالية",
        "new_passwd" to "كلمة المرور الجديدة",
        "save_passwd" to "حفظ التغييرات",
        "receptionist" to "موظف الاستقبال والموايد"
    )

    private val fr = mapOf(
        "app_name" to "MedSync",
        "tagline" to "Système Médical et Santé IA",
        "welcome" to "Bienvenue",
        "role_select" to "Sélectionnez votre rôle d'accès",
        "doctor" to "Médecin / Personnel Médical",
        "nurse" to "Infirmier / Personnel Clinique",
        "pharmacist" to "Pharmacien",
        "patient" to "Patient / Tuteur",
        "login" to "Se connecter",
        "register" to "Créer un compte",
        "email" to "Adresse Email",
        "password" to "Mot de Passe",
        "phone" to "Numéro de Téléphone",
        "specialization" to "Spécialisation Médicale",
        "emergency_contact" to "Contact d'Urgence",
        "fullname" to "Nom Complet",
        "submit" to "Soumettre et Continuer",
        "logout" to "Déconnexion Sécurisée",
        "today_appointments" to "Rendez-vous d'aujourd'hui",
        "quick_actions" to "Actions Rapides",
        "ai_assistant" to "IA Med-Assistant",
        "ai_insight_bp" to "Le patient #8821 présente une variabilité de la TA de +15%. Examen requis avant la visite du soir.",
        "open_insights" to "Ouvrir l'assistant",
        "stats_appointments" to "Rendez-vous Actifs",
        "stats_pending" to "Rapports en attente",
        "telehealth" to "Téléconsultation",
        "in_person" to "Consultation en personne",
        "see_all" to "Voir Tout",
        "due_soon" to "Bientôt Échu",
        "new_alert" to "+3 Nouveaux Aujourd'hui",
        "chat_placeholder" to "Symptômes, interactions médicamenteuses...",
        "send" to "Envoyer",
        "clear_chat" to "Effacer l'historique",
        "sos_button" to "URGENCE SOS",
        "sos_pulsing" to "Appuyez pour envoyer la localisation GPS & alertes",
        "sos_sent" to "Alerte SOS envoyée ! Les secours sont en route.",
        "pharmacy_inventory" to "Inventaire Pharmacie & Alertes",
        "medication_name" to "Nom du Médicament",
        "category" to "Catégorie",
        "stock" to "Stock Restant",
        "price" to "Prix Unitaire",
        "barcode_scan" to "Simuler un Scan Barcode",
        "add_medication" to "Ajouter un Médicament",
        "low_stock" to "ALERTE STOCK FAIBLE !",
        "prescription_mgr" to "Prescriptions Numériques & QR Code",
        "signature_pad" to "Signature Autographe du Médecin",
        "clear_signature" to "Effacer",
        "verify_qr" to "Vérifier le Code QR Médical",
        "drug_interaction_warning" to "ATTENTION: Interaction potentielle détectée entre AINS et inhibiteurs de l'ECA.",
        "settings_title" to "Paramètres & Synchronisation Cloud",
        "sync_now" to "Forcer la Synchronisation (Firestore)",
        "offline_mode" to "Mode Hors-ligne Sécurisé Activé",
        "language_toggle" to "Langue du système",
        "empty_appointments" to "Aucun rendez-vous planifié aujourd'hui",
        "analytics_summary" to "Analyses Cliniques & Données de Performance"
    )

    fun t(key: String, lang: Language): String {
        return when (lang) {
            Language.AR -> ar[key] ?: en[key] ?: key
            Language.FR -> fr[key] ?: en[key] ?: key
            else -> en[key] ?: key
        }
    }
}
