package com.example.utils

import com.example.presentation.LanguageCode

object Loc {
    fun get(code: LanguageCode, key: String): String {
        return dict[code]?.get(key) ?: dict[LanguageCode.EN]?.get(key) ?: key
    }

    private val dict = mapOf(
        LanguageCode.EN to mapOf(
            "app_title" to "MedSync Social",
            "app_subtitle" to "Clinical Network & Intelligence Engine",
            "tab_home" to "Home Feed",
            "tab_assistant" to "AI Counsel",
            "tab_messages" to "Chat Clinic",
            "tab_communities" to "Circles",
            "tab_notifications" to "Alerts",
            "tab_profile" to "My Profile",
            "tab_admin" to "Ops Sync",
            "sos_btn" to "URGENT CLINICAL SOS",
            "sos_subtitle" to "Signal immediate cardiovascular or ICU assistance",
            "fol_count" to "Followers",
            "following_count" to "Following",
            "create_post_hint" to "Have a clinical scenario, research case, or medical query?",
            "post_btn" to "Publish Case",
            "comment_hint" to "Write clinical feedback...",
            "comment_btn" to "Reply",
            "verified" to "Verified Professional",
            "publications" to "Research Publications",
            "switch_user_label" to "Impersonate Node Profile",
            "verify_badge" to "Verified Medical Licensure",
            "admin_title" to "IT Ops & System Control Room",
            "admin_desc" to "Configure safety scores, verification registers, and local caches",
            "toxicity_score" to "AI Toxicity Index",
            "flagged_post" to "Flagged as unverified medical statement",
            "join_circle" to "Join",
            "leave_circle" to "Leave",
            "member" to "Member",
            "members" to "Members",
            "posts" to "Posts",
            "clinical_only" to "Doctor & Staff Eyes Only",
            "public_access" to "Public Education & Support",
            "pharmacy" to "Pharmacological Circles",
            "symptom_title" to "Interactive Symptom Assessment Flow",
            "symptom_desc" to "Enter clinical symptoms. Direct REST call queries Gemini model and gives diagnostic advice or references guidelines.",
            "symptom_placeholder" to "e.g., Patient over age 50 shows deep chest tightness and dyspnea on effort..."
        ),
        LanguageCode.AR to mapOf(
            "app_title" to "ميدسينك الاجتماعي",
            "app_subtitle" to "شبكة التواصل والذكاء الاصطناعي الطبي",
            "tab_home" to "الرئيسية",
            "tab_assistant" to "الذكاء الطبي",
            "tab_messages" to "محادثات المشفى",
            "tab_communities" to "الدوائر",
            "tab_notifications" to "التنبيهات",
            "tab_profile" to "الملف الشخصي",
            "tab_admin" to "إدارة الأنظمة",
            "sos_btn" to "نداء طوارئ سريري عاجل",
            "sos_subtitle" to "تنبيه طواقم الطوارئ والعناية المركزة فورياً",
            "fol_count" to "المتابعين",
            "following_count" to "المتابعون",
            "create_post_hint" to "هل لديك سيناريو سريري أو دراسة بحثية أو استفسار طبي؟",
            "post_btn" to "نشر الحالة",
            "comment_hint" to "اكتب تعليقاً طبياً فاحصاً...",
            "comment_btn" to "إرسال رد",
            "verified" to "كادر طبي موثّق مسبقاً",
            "publications" to "الأوراق والبحوث المنشورة",
            "switch_user_label" to "تبديل الملف الشخصي للمعلم",
            "verify_badge" to "ترخيص طبي معتمد ومفعل",
            "admin_title" to "غرفة المراقبة وإدارة النظم",
            "admin_desc" to "أدوات التحقق من المستندات وفحص معدلات أمان الكلمات ومزامنة قواعد البيانات",
            "toxicity_score" to "مقياس الفحص الذكي للذكاء الاصطناعي",
            "flagged_post" to "تم حظر المنشور كادعاء طبي غير موثق مسبقاً",
            "join_circle" to "انضمام للرابطة",
            "leave_circle" to "مغادرة",
            "member" to "عضو",
            "members" to "أعضاء",
            "posts" to "منشور",
            "clinical_only" to "للطواقم الطبية والدكاترة فقط",
            "public_access" to "ثقافة عامة لمرضى العيادات الخارجية",
            "pharmacy" to "مجموعات العلوم الدوائية",
            "symptom_title" to "الفحص الطوبولوجي للأعراض المرضية",
            "symptom_desc" to "أدخل تفاصيل تشخيصية. يستعلم نموذج جميني بالذكاء الاصطناعي ويحلل المخرجات والمسارات الدلالية الآمنة.",
            "symptom_placeholder" to "مثال: مريض يفوق عمره الستين يشتكي من ضيق حاد في الصدر وعسر تنفس مجهد..."
        ),
        LanguageCode.FR to mapOf(
            "app_title" to "MedSync Réseau",
            "app_subtitle" to "Réseau Clinique & Intelligence Artificielle",
            "tab_home" to "Fil d'actualité",
            "tab_assistant" to "Conseil IA",
            "tab_messages" to "Discussions",
            "tab_communities" to "Cercles",
            "tab_notifications" to "Alertes",
            "tab_profile" to "Profil",
            "tab_admin" to "Opérations Sync",
            "sos_btn" to "SOS CLINIQUE URGENT",
            "sos_subtitle" to "Alerter immédiatement les soins intensifs ou cardiologie",
            "fol_count" to "Abonnés",
            "following_count" to "Abonnements",
            "create_post_hint" to "Avez-vous un cas clinique, une recherche ou une question médicale?",
            "post_btn" to "Publier le cas",
            "comment_hint" to "Rédiger un avis clinique...",
            "comment_btn" to "Répondre",
            "verified" to "Spécialiste Certifié",
            "publications" to "Publications de Recherche",
            "switch_user_label" to "Changer de session de test",
            "verify_badge" to "Licence de Médecine Validée",
            "admin_title" to "Centre d'Opérations et Contrôle",
            "admin_desc" to "Configurer la sécurité, vérifier les praticiens et cloner la base de données",
            "toxicity_score" to "Index Toxicité IA",
            "flagged_post" to "Signalé comme déclaration médicale non vérifiée",
            "join_circle" to "S'abonner",
            "leave_circle" to "Se désabonner",
            "member" to "Membre",
            "members" to "Membres",
            "posts" to "Articles",
            "clinical_only" to "Pour Praticiens Exclusif",
            "public_access" to "Éducation Publique et Soutien",
            "pharmacy" to "Cercles Pharmacologiques",
            "symptom_title" to "Analyse Interactive des Symptômes",
            "symptom_desc" to "Entrez vos symptômes. Notre moteur interroge directement l'IA Gemini pour obtenir un pré-diagnostic indicatif.",
            "symptom_placeholder" to "ex. Patient de 55 ans souffrant de dyspnée d'effort modérée..."
        )
    )
}
